//
// Created by bruce on 9/05/20.
//
#include <fs/fs.h>
#include "unit_test.h"

int main(){
    init_bitmap();
    reset_fs();
    current = curr_scheduling_proc;

    // run_all_tests is generated by tools/utest_generator.py
    run_all_tests();

    printf("unit test passed\n");
    return 0;
}

