
obj-y += abort.o env.o getenv.o putenv.o raise.o rand.o setenv.o strlcpy.o memmov.o \
		strerror.o memcpy.o strcmp.o _strlen.o memset.o index.o strstr.o strcspn.o \
		strspn.o __assert.o strlcat.o strdup.o