#ifndef _STDLIB_H_
#define _STDLIB_H_ 1

#include <stddef.h>
#include <sys/debug.h>
#include <sys/syscall.h>

extern const char **_environ;
const char** get_environ();

#define environ get_environ()

#ifndef NULL
#define	NULL		((void *)0)
#endif

#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#define RAND_MAX       32767    /* largest value generated by rand() */

typedef struct { int quot, rem; } div_t;
typedef struct { long quot, rem; } ldiv_t;

void* malloc (size_t size);
void free(void *ptr);
void* realloc(void *p,size_t size);
void *calloc(size_t number , size_t size);
char *getenv(const char *name);
int putenv(char *name);
int setenv(const char *name, const char *value, int overwrite);
void srand(unsigned int seed);
int rand(void);
long strtol(const char * nptr, char ** endptr, int base);
unsigned long strtoul(const char * nptr, char ** endptr, int base);
void abort();


#define exit(code)      __exit(code)

#endif
