# SPDX-License-Identifier: GPL-2.0
# ==========================================================================
# Building
# ==========================================================================

include tools/Kbuild.include

PHONY := all __clean

all: __cleanall
	$(Q)rm -f $(SREC_INCLUDE)/*.verbose
	$(Q)rm -f $(SREC_INCLUDE)/*.srec

__cleanall: $(obj)
$(obj): FORCE
	$(Q)$(MAKE) $(clean)=$@


FORCE:

.DELETE_ON_ERROR:



