
obj-y += alarm.o     execve.o  perror.o  ipc.o     setpgid.o     sigprocmask.o  sysconf.o    wait.o\
			brk_sbrk.o  _exit.o   getpgid.o  kill.o    sigaction.o   sigsuspend.o   sys_winfo.o\
			errno.o     fork.o    getpid.o   printf.o  sigpending.o  _syscall.o     times.o \
			fs_syscall.o fcntl.o csleep.o

asm-y += wramp_syscall.o __vfork.o __sigreturn.o debug.o