obj-y += ls.o test.o stat.o cat.o echo.o uptime.o wc.o \
	grep.o cp.o rm.o mv.o touch.o mkdir.o history.o \
	ps.o pwd.o df.o du.o snake.o ln.o

srec-y += ls.srec test.srec stat.srec cat.srec echo.srec \
	uptime.srec wc.srec grep.srec cp.srec rm.srec mv.srec \
	touch.srec mkdir.srec history.srec ps.srec pwd.srec \
	df.srec du.srec snake.srec ln.srec


ls.srec = ls.o
test.srec = test.o
stat.srec = stat.o
cat.srec = cat.o
echo.srec = echo.o
uptime.srec = uptime.o
wc.srec = wc.o
grep.srec = grep.o
cp.srec = cp.o
rm.srec = rm.o
mv.srec = mv.o
touch.srec = touch.o
mkdir.srec = mkdir.o
history.srec = history.o
ps.srec = ps.o
pwd.srec = pwd.o
df.srec = df.o
du.srec = du.o
snake.srec = snake.o
ln.srec = ln.o

