obj-y += ls.o test.o stat.o cat.o echo.o uptime.o wc.o grep.o

srec-y += ls.srec test.srec stat.srec cat.srec echo.srec uptime.srec wc.srec grep.srec
ls.srec = ls.o
test.srec = test.o
stat.srec = stat.o
cat.srec = cat.o
echo.srec = echo.o
uptime.srec = uptime.o
wc.srec = wc.o
grep.srec = grep.o