obj-y += ls.o test.o stat.o cat.o echo.o uptime.o

srec-y += ls.srec test.srec stat.srec cat.srec echo.srec uptime.srec
ls.srec = ls.o
test.srec = test.o
stat.srec = stat.o
cat.srec = cat.o
echo.srec = echo.o
uptime.srec = uptime.o